const bk = {
    'PHP CS': { title: '', url: 'https://overapi.com/php', des: '' },
    'Java CS': { title: '', url: 'https://overapi.com/java', des: '' },
    'Java ': { title: '', url: '', des: '' },
    'Express CS': { title: '', url: 'https://overapi.com/express', des: '' },
    'Express ': { title: '', url: '', des: '' },
    'Python CS': { title: '', url: 'https://overapi.com/python', des: '' },
    'Pthon ': { title: '', url: '', des: '' },
    'Node.js CS': { title: '', url: 'https://overapi.com/nodejs', des: '' },
    'Laravel cs': { title: '', url: 'https://learninglaravel.net/cheatsheet/', des: '' },
    'laravel': { title: '', url: 'https://www.tutorialspoint.com/laravel/index.htm', des: '' },
    'Wordpress cs': { title: '', url: 'https://overapi.com/wordpress', des: '' },
    'PHP ': { title: '', url: 'https://www.tutorialspoint.com/php/index.htm', des: '' },
    'Electron cs': { title: '', url: 'https://simulatedgreg.github.io/electron-cheatsheet/', des: '' },
    'VS': { title: '', url: 'https://visualstudio.microsoft.com/keyboard-shortcuts.pdf', des: '' },
    'Electron ': { title: '', url: 'https://www.tutorialspoint.com/electron/index.htm', des: '' },
    'IntellJIdea': { title: '', url: 'https://gist.github.com/hopbit/42d20139d98f63b9a9b5', des: '' },
    'chrome Ex': { title: '', url: 'https://developer.chrome.com/docs/extensions/mv3/getstarted/', des: '' },
    'ElasticSearch': { title: '', url: '', des: '' },
    'GraphQL': { title: '', url: '', des: '' },
    'Streaming': { title: '', url: '', des: '' },
    'JWT': { title: '', url: '', des: '' },
    'SSO': { title: '', url: '', des: '' },
    'Design Pat': { title: '', url: '', des: '' },
    'Solid': { title: '', url: '', des: '' },
    'Concurrency': { title: '', url: '', des: '' },
    'Scalability': { title: '', url: '', des: '' },
    'WebSockets': { title: '', url: '', des: '' },
    'Load Testing': { title: '', url: '', des: '' },
    'Big Data': { title: '', url: '', des: '' },
    'Security': { title: '', url: '', des: '' },
    'n-tier Arch': { title: '', url: '', des: '' },
    'Cost Optmzn': { title: '', url: '', des: '' },
    'Low Latency': { title: '', url: '', des: '' },
}

export default bk